projects:
    type:     rest
    resource: AppBundle\Controller\ProjectController

phrases:
    type:     rest
    resource: AppBundle\Controller\PhraseController

translations:
    type:     rest
    resource: AppBundle\Controller\TranslationController

security:
    type:     rest
    resource: AppBundle\Controller\SecurityController
